### ISSUE TITLE
Choose Title for the book in Portuguese

### ISSUE THREAD

**Issue by joaopgrassi** [joaopgrassi/little-aspnetcore-book#11]
The original title of the book is **_Little ASP.NET Core Book_**. If we literally translate that to Portuguese it will be:

_**O pequeno livro de ASP.NET Core.**_

Apart from being too long, at least to me, it sounds kind of silly and very unprofessional. Don't think people would take it seriously with a name like that.

If I captured the concept of the book correctly, it's a short, introductory, succinct and to the point book that brings developers quickly into speed on ASP.NET Core "world".

Having that in mind, my suggestion is to use this Title instead:

**_ASP.NET Core - Guia de bolso_**

That translates into English as: ASP.NET Core - Pocket guide.

I think this is much better. There's several tech books that follow this pattern already in pt-BR, like this one: http://www.altabooks.com.br/c-guia-de-bolso.html. 

What do you guys think? @nicolastarzia @nbarbettini

**Comment by nicolastarzia** [comment]
I agree, "ASP.NET Core - guia de bolso" sounds amazing to me...

**Comment by joaopgrassi** [comment]
Agreed with the title: ASP.NET Core - Guia de Bolso.
