### ISSUE TITLE
Add external packages

### ISSUE THREAD

**Issue by joaopgrassi** [joaopgrassi/little-aspnetcore-book#4]
"Issue" to track translation of the `Add external packages` Chapter

**Comment by joaopgrassi** [comment]
@oliveiramarcio I think you created the chapter/add-external-packages in your fork from `master` and not from `pt-br`. You'll need to re-open a PR for that translation. I didn't see it and I ended up merging it into `master`.

**Comment by oliveiramarcio** [comment]
Oh my bad! I'll fix it today. I guess I picked wrong branch on GitHub Desktop when I created this one... =( Sorry!

**Comment by joaopgrassi** [comment]
closed by #18
