### ISSUE TITLE
Use a database

### ISSUE THREAD

**Issue by joaopgrassi** [joaopgrassi/little-aspnetcore-book#5]
"Issue" to track translation of the `Use a database` Chapter

**Comment by oliveiramarcio** [comment]
Done translation of "README.md" file.

[https://github.com/oliveiramarcio/little-aspnetcore-book/commit/a64783d9b7ef32c8bf10afe2bef1b92a15d4513a]

**Comment by oliveiramarcio** [comment]
Done translation of "connect-to-a-database.md" file.

**Comment by oliveiramarcio** [comment]
Done translation of "update-context.md" file and corrections on "connect-to-a-database.md" file.

**Comment by oliveiramarcio** [comment]
Done translation of "create-migration.md" file and corrections on "connect-to-a-database.md" and "update-context.md" files.

**Comment by oliveiramarcio** [comment]
Done translation of "create-service-class.md" file.

**Comment by oliveiramarcio** [comment]
Created pull request to review and merge.

**Comment by joaopgrassi** [comment]
Merged #19
